"use client";

import React from "react";
import Image from "next/image";
import { motion } from "framer-motion";
import { Layers, CheckCircle2 } from "lucide-react";

export default function Philosophy() {
  return (
    <section id="philosophy" className="py-24 relative overflow-hidden">
      {/* Subtle ambient lighting */}
      <div className="absolute top-1/2 left-0 w-[500px] h-[500px] bg-[#ff5500]/10 blur-[150px] pointer-events-none -z-10" />

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Top Eyebrow + Manifesto Statement (Directly matching inspo-1) */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start mb-16">
          <div className="lg:col-span-3">
            <span className="text-xs font-mono font-semibold tracking-wider text-[#ff6b00] uppercase">
              01/ philosophy
            </span>
          </div>

          <div className="lg:col-span-9">
            <motion.h2
              initial={{ opacity: 0, y: 15 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6 }}
              className="text-2xl sm:text-4xl lg:text-5xl font-light text-zinc-100 leading-snug tracking-tight"
            >
              We don&apos;t just make things move. We build the{" "}
              <span className="font-semibold text-transparent bg-clip-text bg-gradient-to-r from-[#ff5500] via-[#ff7a00] to-[#ffa500]">
                visual narrative
              </span>{" "}
              that supports your product&apos;s growth. Engineering motion for visionaries.
            </motion.h2>

            <motion.p
              initial={{ opacity: 0, y: 15 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.6, delay: 0.1 }}
              className="mt-6 text-base text-zinc-400 max-w-2xl leading-relaxed"
            >
              A technically impressive animation is not enough if the viewer does not understand what the product does. Likewise, a clear explanation should never feel visually generic. We bring together strategy, storytelling, design, and motion to make software unforgettable.
            </motion.p>
          </div>
        </div>

        {/* Bento Grid (Matching inspo-1 3-card structure) */}
        <div className="grid grid-cols-1 md:grid-cols-12 gap-6 items-stretch">
          
          {/* Card 1: DECONSTRUCT. STRUCTURE. ELEVATE. */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
            className="md:col-span-4 p-8 rounded-3xl bg-[#101012] border border-white/[0.08] flex flex-col justify-between hover:border-[#ff7a00]/30 transition-all duration-300 group shadow-card-glow"
          >
            <div>
              <div className="flex items-center justify-between mb-8">
                <span className="text-[11px] font-mono tracking-widest text-zinc-400 uppercase">
                  OUR CORE FORMULA
                </span>
                <div className="w-8 h-8 rounded-full bg-white/[0.04] border border-white/10 flex items-center justify-center text-[#ff6b00]">
                  <Layers className="w-4 h-4" />
                </div>
              </div>

              <h3 className="text-xl font-bold text-white tracking-tight leading-snug mb-3 uppercase">
                DECONSTRUCT. <br />
                STRUCTURE. <br />
                ELEVATE.
              </h3>

              <p className="text-xs text-zinc-400 leading-relaxed">
                We strip away the digital noise to find the core message of your business. By structuring complex software capabilities into high-end UX/UI motion, we create digital narratives that command authority and drive user adoption.
              </p>
            </div>

            <div className="mt-8 pt-6 border-t border-white/[0.06] flex items-center gap-2 text-xs font-semibold text-zinc-300">
              <span className="text-[#ff6b00]">Strategy</span>
              <span className="text-zinc-600">+</span>
              <span className="text-[#ff7a00]">Story</span>
              <span className="text-zinc-600">+</span>
              <span className="text-[#ffa500]">Design</span>
              <span className="text-zinc-600">+</span>
              <span className="text-white">Motion</span>
            </div>
          </motion.div>

          {/* Card 2: Architectural Amber Visual generated by Gemini */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6, delay: 0.1 }}
            className="md:col-span-4 relative rounded-3xl overflow-hidden min-h-[300px] border border-white/[0.08] group shadow-card-glow flex items-end p-6 bg-black"
          >
            <Image
              src="/images/bento_tunnel.jpg"
              alt="Architectural Motion Space"
              fill
              sizes="(max-width: 768px) 100vw, 33vw"
              className="object-cover transition-transform duration-700 group-hover:scale-105"
            />
            {/* Ambient overlay */}
            <div className="absolute inset-0 bg-gradient-to-t from-black/85 via-black/25 to-transparent" />
            
            <div className="relative z-10 w-full">
              <span className="text-[10px] uppercase font-mono tracking-wider text-[#ffa500] px-2.5 py-1 rounded-full bg-black/70 backdrop-blur-md border border-white/10">
                Spatial Atmosphere
              </span>
              <p className="text-sm font-semibold text-white mt-2">
                Cinematic atmosphere engineered for high-growth tech brands.
              </p>
            </div>
          </motion.div>

          {/* Card 3: Zero Templates (White / Frosted Glass card matching inspo-1) */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="md:col-span-4 p-8 rounded-3xl bg-white text-[#09090b] flex flex-col justify-between shadow-2xl relative overflow-hidden group"
          >
            {/* Top 3 dots matching inspo-1 */}
            <div className="flex items-center justify-between mb-8">
              <span className="text-[11px] font-mono tracking-widest text-zinc-500 uppercase font-semibold">
                CRAFT GUARANTEE
              </span>
              <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-zinc-100 border border-zinc-200">
                <span className="w-2 h-2 rounded-full bg-[#ff5500]" />
                <span className="w-2 h-2 rounded-full bg-amber-400" />
                <span className="w-2 h-2 rounded-full bg-zinc-300" />
              </div>
            </div>

            <div>
              <h3 className="text-2xl sm:text-3xl font-extrabold text-[#09090b] tracking-tight mb-3">
                Zero Templates
              </h3>
              <p className="text-xs sm:text-sm text-zinc-600 leading-relaxed font-normal">
                We design from absolute scratch. Every visual solution by Spline Motion is tailored exclusively to your business objectives, ensuring a distinctive market presence that cannot be replicated.
              </p>
            </div>

            <div className="mt-8 pt-6 border-t border-zinc-200 flex items-center justify-between">
              <div className="flex items-center gap-2">
                <CheckCircle2 className="w-4 h-4 text-[#ff5500]" />
                <span className="text-xs font-semibold text-zinc-800">100% Custom Keyframes</span>
              </div>
              <span className="text-xs font-mono text-zinc-500">0% Stock</span>
            </div>
          </motion.div>

        </div>

      </div>
    </section>
  );
}
